Fix Errors when value is **null**
1TGDev/mysql-database pull request #6
Opened 2021-11-15 16:07 UTC by abdooo9

احيانا  ممكن المستخدم يحط null 
ب value

السبب هو انه ممكن يكون عنده object ب value مثلا
```js
{
   avatar: "AVATAR_CODE",
   username: "USERNAME"
}
```

بالطبيعي رح تسجل الداتا هيك
```js
const user_obj ={
   avatar: "AVATAR_CODE",
   username: "USERNAME"
}

await db.set("users", "USER_ID", user_obj)
```
ممكن المتسخدم يشيل ال avatar
وقتها رح يسجل هيك
```js
await db.set("users", "USER_ID.avatar", null)
```
يعني ماله افاتار

المشكلة انه بالمكتبة لما اسجل null ما يقبل 

المفروض ما يقبل undefined
لأن كمنطق
```js
function my_function(param) {
   return param
} 
my_function() // undefined
my_function("my_param") // "my_param"
```

الحل انه غيرت من 
```js
if (value == null) throw new TypeError(errors.value.replace("{received}", value))
```
الى
```js
if (value === undefined) throw new TypeError(errors.value.replace("{received}", value))
```
عشان يكون أصح كمنطق وأقدر أسجل null 
لأن بالعادة ما أـوقع أحد يسجل undefined

2021-11-15 16:11 UTC, FnrDev commented on structures/methods/add.js
> +	if(value === undefined) throw new TypeError(errors.value.replace("{received}", value));
Why don't change it to `if (!value) ...` it will check falsely values

2021-11-15 16:22 UTC, FnrDev requested changes
Change from
```js
if (value === undefined)
```
to
```js
if (!value)
```

2021-11-15 16:58 UTC, abdooo9 reviewed
Updated from ``if(value === undefined)`` to ``if(!value)``

2021-11-15 17:00 UTC, FnrDev approved these changes

2021-11-16 07:30 UTC, abdooo9 commented
Undo it to ``if(value === undefined)``

2021-11-16 07:30 UTC, abdooo9 reviewed
Undo it to ``if(value === undefined)``

2021-11-20 09:41 UTC, closed without merging